# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@master

    - name: 'Test'
      run: dub test --compiler=$DC --coverage -- -s -t -d
    - name: 'Build'
      run: dub build --compiler=$DC
    - name: 'Docs'
      run: dub build --compiler=$DC --build=ddox
